server:
  port: 1080

spring:
  dataSoruce:
    url: jdbc:mysql://localhost:3306/zjj?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    history-level: full #保存历史数据级别设置为full最高级别，便于历史数据的追溯

